### ISSUE TITLE
When deleting an app in the middle of deployment after the vm was created in azure will end with it staying there

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#134]
STR
Have an reservation with deployed azure app 
Add an azure app 
Run deploy command
in azure portal wait for until the vm is created
In the cloudshell portal delete the app 

BIR
The vm stays live in azure without any connection to cloudshell

**Comment by alexazarh** [comment]
@tornizanQ - I think this happens also in the AWS and other cloud provider... its kinda a limitation of our system. Or am I missing something?
So maybe we can lower the priority?
And maybe the actual the bug is that you can delete an app during deployment or that you can not cancel a deployment of an app?

**Comment by TomerAdmon** [comment]
@tornizanQ  @alexazarh  - what we should do with this one?

**Comment by TomerAdmon** [comment]
known limitation.... closing
