### ISSUE TITLE
DeployVM: POC for using json instead of regular api

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#199]
as first step, we need to know how it will help us in terms of performance and how much development it will require.

**Comment by alexazarh** [comment]
example:
https://azure.microsoft.com/en-us/resources/samples/resource-manager-python-template-deployment/

**Comment by igoro1975** [comment]
@TomerAdmon , @alexazarh 
POC results.
We didn't find the way to run the entire deploy process with one template because the resources created or updated during the process located in different resource groups.
We tried to improve performance for the most time-consuming parts of deploy (creation of the security rules, each one takes 10 seconds via API) and found that:
1) If we wait for the result of the template processing, it takes more than 30 seconds.
2) If we just send the template without waiting the result, we have multi-deploying issues.
So meanwhile the refactoring and templates do not improve performance for the process.
