### ISSUE TITLE
QualiX for Azure (portal side)

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#245]

**Comment by TomerAdmon** [comment]
To support Azure shell in QualiX, we will change the way the Quali Server is generating links for QualiX, to make sure PEM files will be transferred securely. 

changes should be backword compatible so customers that use 7.1 for example and won't use Azure in 7.2 will be able to work with the old configuration and everything will work fine.

Task description:
http://confluence.quali.com/pages/viewpage.action?pageId=29655502

**Comment by alexazarh** [comment]
How to handle exceptions from QualiX?

**Comment by TomerAdmon** [comment]
Error handling: 
- Any error generating the url to the new controller - pop-up notification
- Any error in the POST - should give the user a robot page (since this is a new window)
- Problems in the QualiX side (token was generated bug the session gives white page) - need to investigate    whether it's possible to identify those in a webClient in the portal before the redirect

also in here: http://confluence.quali.com/pages/viewpage.action?pageId=29655502

**Comment by TaiTheGreat** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=158791)

**Comment by Shnitselon** [comment]
updated 8.0 EA QualiX documentation with the new codes + explanations on input params, at: \\qsnas1\Shared\steven.g\QualiX 2.4
#TaiTheGreat #TomerAdmon
