### ISSUE TITLE
If vhd OS and OS type attribute do not match, vhd is copied but the deploy goes on and on

### ISSUE THREAD

**Issue by TaiTheGreat** [QualiSystems/Azure-Shell#287]
1. Create a custom image app using a linux vhd and mark its "OS type" as "windows".
2. Add to a blueprint and reserve.

BIR if the vhd is copied to the sandbox's storage account but the deploy command just keeps running.

**Comment by apiddubny** [comment]
We can't check if the provided VHD image is a Linux or Windows type, actually that is why we need "Image OS Type" attribute

**Comment by alexazarh** [comment]
We should get a timeout after some time so be patient and make sure the error message is clear

**Comment by tornizanQ** [comment]
@TomerAdmon @alexazarh , I think we are should try to make this error a little bit more clear that the problem is the os type did not match. 
The error given now is:




Error description: Azure Error: OSProvisioningTimedOut
Message: OS Provisioning for VM 'azurecus1c3ea8156c6f4488' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later. Also, make sure the image has been properly prepared (generalized).

 * Instructions for Windows: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-upload-image/ 

 * Instructions for Linux: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-capture-image/ 

Parameters:

**Comment by TomerAdmon** [comment]
Hi, 
let's keep this error and add: "This error may happen when there is a mismatch between the OS type and the image URN specified".
@alexazarh @apiddubny  - please investigate when it's possible to get OSProvisioningTimedOut, just to make sure that we are not associating other errros to this one.

**Comment by apiddubny** [comment]
@TomerAdmon @alexazarh 
Seems that OSProvisioningTimedOut error may occur in many cases (Image wasn't properly generalized, image is to large and it takes a lot of time to deploy it, etc)
https://github.com/Azure/azure-sdk-for-node/issues/1491
I'm not sure that it is good idea to extend error message from azure since it some common one there for "something went wrong"

**Comment by TomerAdmon** [comment]
OK, 
we will go with this approach:
if -> deployment type is deploy vm from custom image
and -> we are getting this error
we will add this line to the error thrown from Azure:
"You may have a mismatch between the selected ‘Image OS Type’ and the operation system provided in the ‘Image URN’. "

**Comment by tornizanQ** [comment]
It is now reproduces as first described by Tai. The deployment  stucks and taking over an hour

**Comment by TomerAdmon** [comment]
@tornizanQ  - but this error appears? "You may have a mismatch between the selected ‘Image OS Type’ and the operation system provided in the ‘Image URN’. "

**Comment by tornizanQ** [comment]
no it is just running, over an hour by now
