### ISSUE TITLE
AWS / vCenter Refactoring - Cloud Provider

### ISSUE THREAD

**Issue by menib** [QualiSystems/Azure-Shell#30]
- The Apps infrastructure now supports a special field for Cloud Provider. 
- The existing shells (vCenter, AWS) include the cloud provider name / vcenter name as an attribute on all the deployment types. 
- We need to align with the new infrastructure by refactoring all deployment types:  
  > Remove the Cloud Provider / vCenter name attribute from the shell package
  > Update the drivers and  scripts to take the value from the app context instead of the attribute.

**Comment by alexazarh** [comment]
The code should be backward compatible.
If the new Cloud Provider field doesnt exist in the context than the fallback should be the cloud provider  / vcenter name attribute

**Comment by alexazarh** [comment]
I missed the point that if we remove an attribute it cannot be backwards compatible because this shells are coming OOB with CloudShell. 
So we need need to increase the minor version.
vCenterShell 1.3.X => 1.4.0
AWS-Shell 1.0.X => 1.1.0

@apiddubny - please make the relevant change in the version.txt files and update the requirements accordingly

**Comment by GilGald** [comment]
@alexazarh ,can you explain why it will solve the problem?

**Comment by alexazarh** [comment]
because when we increase a minor version it means we introduced a braking change

**Comment by yairbb** [comment]
@alexazarh @menib is that story connected to Azure ?

**Comment by tornizanQ** [comment]
Blocked by #398
