### ISSUE TITLE
After extension script fails with timeout the vm is stuck on powering on

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#369]
STR
1.Have a vm with faulty extension script
2.change the extension script timeout to 60
3.Reserve the environment 
4.wait for the extension script to fail with time out (an error should appear in the output of the reservation)

BIR
The VM will try to power on for a long period of time (more than 30 min)

In azure portal the machine is running

**Comment by alexazarh** [comment]
Expected behavior:
In a scenario where an app have custom extension and it reached a timeout, we would like to throw an error in the power-on phase to indicate that the app is not deployed successfully. we will also attach a live status that shows an error.

Implementation:
1. Add a property to the DeployResult in the deploy operation that will indicate if there was a timeout during custom script extension. 
PropName: "extension_time_out",  PropValues: "true"/"false"
2. In the power on command, before we call the Azure api we should check the "extension_time_out" property in the custom params of the vm details. 
3. In case of "extension_time_out" == "true" we will set live status on the VM to "Error" with a message: "Partially deployed app". And after this we will throw an exception so that the sandbox status will be active with error. The exception message will be: "Partially deployed app: VM Custom Script Extension failed to compete within the specified timeout"

Technical note:
please implement this inside the power_vm_operation and not in azure_shell.py

Documentation note:
In a scenario where an app gets an "error" live status and a message referring to an extension timeout, this app didn't completed the extension installation process and kept on just for debugging the error. this app is not in an operational state and it will not be possible to power on the app using CloudShell. teardown process will terminate the app as always.
