### ISSUE TITLE
Investigate how sessions work in Azure clients

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#99]
We need to understand what is the expiration timeout for the Azure clients when idle.
And how to work with refresh token url.

**Comment by apiddubny** [comment]
Token expiration time is 3600 seconds, but azure clients use
msrest.service_client.send method under the hood. This method catches TokenExpiredError exception and calls refresh_session method, which will re-create token and attach it to the current session. 

So we can initialize only one  creds session (msrestazure.azure_active_directory.ServicePrincipalCredentials) because it actually will  never expires
